### PR TITLE
Added simple macro for Que

### PR DESCRIPTION
**Pull request by mossgross-cf**
Here is a macro that can be used for the Que job queue that we created out of necessity and would like to share it with the community if it will be useful.

### CODE REVIEW

**Comment by meskyanichi** [comment]
Thanks @mossgross-cf!

Is it for this lib? https://github.com/chanks/que

**Comment by mrrooijen** [comment]
@prognostikos I wouldn't mind merging this back into master and including it in the official gem if it's still applicable. Could you check if @mossgross-cf's branch works with your app?

```ruby
gem "hirefire-resource",
  github: "CrowdFlower/hirefire-resource",
  branch: "task/add-que-macro"
```

**Comment by prognostikos** [comment]
@mrrooijen I've tested this in production for our app and it does work

**Comment by mrrooijen** [comment]
@prognostikos thanks! Just released v0.4.0 which includes Que.

**Pull request merged**
