### PR TITLE
Match Que macro with que/lib/que/poller.rb

### PR DESCRIPTION
**Pull request by defkode**
Fixes Que macro. Finished and expired jobs are not picked up by que poller and should be rejected from calculation.

Also reuse scopes available in que gem: https://github.com/que-rb/que/blob/master/lib/que/sequel/model.rb

### CODE REVIEW

**Comment by mrrooijen** [comment]
Hi @defkode,

Looks good. My only concern is that this ties the macro to ActiveRecord which might not be available in certain environments (and thus, wouldn't be backwards compatible). Would it be possible to make this queryable without relying on ActiveRecord?

**Comment by defkode** [comment]
ActiveRecord interface was added in que https://rubygems.org/gems/que/versions/1.0.0.beta along with expired_at, finished_at fields.

So, the behaviour is different depending on which version is used...

Unfortunately Que 1.0.0 line is still in beta after more than 3 years - I think best way is to add separate matcher (lib/hirefire/macro/que_beta.rb) for QueBeta and comment both, so people are not confused anymore which matchers they should use in their own applications.

**Comment by mrrooijen** [comment]
I meant that Que has a soft-dependency (optional) on ActiveRecord. If we use the ActiveRecord interface in the macro exclusively, then the issue is that people that were previously using the Que macro without Rails+ActiveRecord (i.e. Rails+Sequel or something) wouldn't have a working macro anymore.

I've created a draft PR (see #59) that addresses that issue by incorporating your addition, while maintaining backwards compatibility by defaulting to the plain SQL query of Que `0.x`.

To try this out in your application, use:

```rb
gem "hirefire-resource", github: "hirefire/hirefire-resource", branch: "que-improvements"
```

Call the macro with the `mapper` option: `HireFire::Macro::Que.queue("email", mapper: :active_record)`.

Please take a look and let me know what you think.

**Comment by defkode** [comment]
I left my comment https://github.com/hirefire/hirefire-resource/pull/59

**Pull request closed without merging**
